const propertyData = [
  {
    id: 1,
    title: "Cape Town, South Africa",
    description: "Added 1 week ago",
    location: "",
    price: "AED 800.00",
    img: "/images/1.jpg",
    dateCreated: "",
  },
  {
    id: 2,
    title: "Coco, Costa Rica",
    description: "Added 1 week ago",
    location: "",
    price: "AED 1050.00",
    img: "/images/2.jpg",
    dateCreated: "",
  },
  {
    id: 3,
    title: "Val-des-Monts, Canada",
    description: "Added 4 weeks ago",
    location: "",
    price: "AED 2000.00",
    img: "/images/3.jpg",
    dateCreated: "",
  },
  {
    id: 4,
    title: "Sa Pa, Vietnam",
    description: "Added 1 month ago",
    location: "",
    price: "AED 750.00",
    img: "/images/4.jpg",
    dateCreated: "",
  },
  {
    id: 5,
    title: "Rollag kommune, Norway",
    description: "Added 3 weeks ago",
    location: "",
    price: "AED 500.00",
    img: "/images/5.jpg",
    dateCreated: "",
  },
  {
    id: 6,
    title: "Flores da Cuhna, Brazil",
    description: "Added 1 week ago",
    location: "",
    price: "AED 1200.00",
    img: "/images/6.avif",
    dateCreated: "",
  },
  {
    id: 7,
    title: "Broad Cave, Canada",
    description: "Added 1 week ago",
    location: "",
    price: "AED 3400.00",
    img: "/images/7.webp",
    dateCreated: "",
  },
  {
    id: 8,
    title: "Ubud, Indonesia",
    description: "Added 1.5 weeks ago",
    location: "",
    price: "AED 2000.00",
    img: "/images/8.jpg",
    dateCreated: "",
  },
  {
    id: 9,
    title: "Ubud, Indonesia",
    description: "Added 1.5 weeks ago",
    location: "",
    price: "AED 2000.00",
    img: "/images/9.jpg",
    dateCreated: "",
  },
  {
    id: 10,
    title: "Ubud, Indonesia",
    description: "Added 1.5 weeks ago",
    location: "",
    price: "AED 2000.00",
    img: "/images/10.jpg",
    dateCreated: "",
  },
  {
    id: 11,
    title: "Ubud, Indonesia",
    description: "Added 1.5 weeks ago",
    location: "",
    price: "AED 2000.00",
    img: "/images/11.jpg",
    dateCreated: "",
  },
  {
    id: 12,
    title: "Ubud, Indonesia",
    description: "Added 1.5 weeks ago",
    location: "",
    price: "AED 2000.00",
    img: "/images/12.jpg",
    dateCreated: "",
  },
];

export default propertyData;
